version: 1

python:
  version: 3

engines:
  # Bandit: Ищет распространенные уязвимости безопасности в коде Python. Must-have!
  bandit:
    enabled: true
    # Конфигурация также возможна через pyproject.toml ([tool.bandit...])
    # для исключения определенных проверок или путей.

  # Mypy: Статический анализатор типов. Очень полезен, если используешь аннотации типов.
  mypy:
    enabled: true # Включай, если активно используешь type hints (судя по types.py - да)
    # Mypy требует конфигурации, обычно в pyproject.toml ([tool.mypy...]) или mypy.ini
    # Убедись, что там указаны пути к исходникам (src) и другие нужные флаги.

  # Radon: Измеряет сложность кода (цикломатическая сложность, индекс поддерживаемости).
  radon:
    enabled: true
    # Можно настроить пороги сложности, если стандартные не устраивают.
    # config:
    #   cc_max: 15 # Макс. цикломатическая сложность (пример)

  # Duplication (использует PMD CPD): Находит дублирование кода (copy-paste).
  duplication:
    enabled: true
    config:
      languages:
        - python
      # Можно настроить минимальное количество токенов для срабатывания
      # minimum_tokens: 70 # Стандартно около 100, можно уменьшить для большей чувствительности


# Исключаем директории и файлы из анализа ВСЕМИ инструментами.
exclude_paths:
  # Системные и конфигурационные директории/файлы GitHub Actions
  - ".github/"
  # Бинарные ассеты
  - "assets/"
  # Старая версия кода
  - "v0.1 separated/"
  # Стандартные директории виртуальных окружений
  - "venv/"
  - ".venv/"
  # Артефакты сборки
  - "build/"
  - "dist/"
  - "*.egg-info/"
  # Файлы конфигурации в корне
  - ".codacy.yaml"
  - ".codacy.yml"
  - ".markdownlint.yaml"
  - ".pre-commit-config.yaml"
  - "pyproject.toml"
  - "tox.ini"
  - "uv.lock"
  # Файлы документации и лицензий (если они не содержат исполняемого кода для анализа)
  - "README.md"
  - "README.ru.md"
  - "LICENSE" # Уточни имя файла, если оно другое (у тебя LICENSE(.bib) - возможно, просто LICENSE?)
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "CONTRIBUTING.ru.md"
  - "SECURITY.md"
  # Файлы Git (у тебя с суффиксом .bib - уточни реальные имена)
  - ".gitattributes"
  - ".gitignore"
  # Другие не-Python файлы, которые могут случайно попасться
  - "**.md"
  - "**.bib"
  - "**.ico"
  - "**.icns"
  - "**.png"
  - "CODEOWNERS" # Уточни имя файла
 