name: 🐞 Сообщение об ошибке (Bug Report)
description: Опишите проблему, с которой вы столкнулись
title: "[BUG] Краткое описание проблемы"
labels: ["bug", "needs triage"]
assignees:
  - diam0voi
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Перед созданием:**
        *   Убедитесь, что вы используете **последнюю версию** приложения (проверьте [Releases](https://github.com/diam0voi/RGO-lib-parser/releases)).
        *   Поищите похожие проблемы в [открытых Issues](https://github.com/diam0voi/RGO-lib-parser/issues).
        *   Проверьте раздел [FAQ / Troubleshooting](https://github.com/diam0voi/RGO-lib-parser#faq--troubleshooting) в README.

  - type: textarea
    id: bug-description
    attributes:
      label: 1. Описание ошибки
      description: Четко и кратко опишите, что пошло не так.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 2. Шаги для воспроизведения
      description: Как можно детальнее опишите шаги, которые приводят к ошибке (1. Запустить приложение, 2. Ввести ... в ..., 3. Нажать ...).
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 3. Ожидаемое поведение
      description: Что должно было произойти вместо ошибки?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 4. Фактическое поведение
      description: Что произошло на самом деле? (Например, "Приложение зависло", "Появилось сообщение об ошибке", "Файлы не скачались")
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 5. Скриншоты (необязательно)
      description: Если возможно, приложите скриншоты окон приложения, сообщения об ошибке и т.д. (перетащите файлы сюда).
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 6. Окружение
      description: Пожалуйста, укажите вашу ОС, версию приложения и версию Python (если запускаете из исходников).
      placeholder: |
        *   ОС: macOS Sonoma 14.4
        *   Версия приложения: v1.4
        *   Версия Python: 3.11.5 (если применимо)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 7. Дополнительный контекст
      description: Любая другая информация, которая может помочь (например, ссылка на конкретную книгу).
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 8. Лог-файл (parsing.log)
      description: "**ОЧЕНЬ ВАЖНО!** Приложите содержимое файла `parsing.log` (обычно рядом с программой или в папке данных). Если файл большой, вставьте последние 50-100 строк."
      placeholder: "Вставьте лог сюда..."
      render: log
    validations:
      required: true