version: 2
updates:
  -
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "build"
      include: "scope"
